services:
  postgres:
    image: postgres:16
    container_name: postgres-readjourney
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - readjourney_pgdata:/var/lib/postgresql/data

volumes:
  readjourney_pgdata:
